version: '3'

networks: 
  default:
    external: false
  proxy_default:
    external: true

services:

  wordpress:
    image: myuserindocker/gaziteng-webapp:latest
    volumes:
      # - "$PWD/volume/app:/app"
      # - "$PWD/volume/log:/var/log/apache2"
      - "$PWD/volume/wordpressUploads:/app/root/content/uploads/"
    environment:
      DEPLOYMENT: production
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: WebApp_GazitEng_Database
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=443
        - com.df.srcPort=443
        # - com.df.httpsPort=443
        # - com.df.httpsOnly=true
        - com.df.reqMode=tcp
    networks:
      - default
      - proxy

  mysql:
    image: mysql:latest
    volumes:
        - "$PWD/volume/mysqlData/:/var/lib/mysql"
        - "$PWD/volume/mysqlDatabase/:/docker-entrypoint-initdb.d"
    environment:
        # MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_DATABASE: WebApp_GazitEng_Database
    networks:
      - default

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #   volumes:
  #     - /sessions
  #   extra_hosts:
  #     - "mysql:db"
  #   networks:
  #     - default
  #     deploy:
  #     labels:
  #       - com.df.notify=true
  #       - com.df.distribute=true
  #       - com.df.servicePath=/phpmyadmin
  #       - com.df.port=80
