version: '2.1'

services:

    mysql:
        build:
            context: ../../
            dockerfile: ./setup/container/mysql.dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-WebApp_GazitEng_Database}
        container_name: mysql
        volumes:
            # - "./../volume/mysqlDatabase/:/var/lib/mysql"
            - "../../volume/mysqlDatabase/:/docker-entrypoint-initdb.d"
