version: '2.1'

services:

  wordpress:
    image: myuserindocker/gaziteng-webapp:latest
    container_name: wordpress
    ports:
      - "80:80"
      - "443:443"
    # All mounted volumes with specific host directory, replace the contents/files of the container folder. Thus the solution is to use entrypoint to populate the volume after it is created.
    volumes:
      - "/app/"
      - "/var/log/apache2/"
    environment:
      DEPLOYMENT: 'production'
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-WebApp_GazitEng_Database}
    # entrypoint: updateDefaultEntrypoint.sh

  wordpressBuild:
    extends: wordpress
    build:
      context: ../../
      dockerfile: ./setup/container/wordpress.php5.6.dockerfile
      args:
        - DEPLOYMENT=${DEPLOYMENT:-production}
    # name of local image to be built
    environment:
        DEPLOYMENT: ${DEPLOYMENT:-production}
